### ISSUE TITLE
downloads/examples

### ISSUE THREAD

**Issue by amazein** [sbgn/sbgn.github.io#1]
There is "examples" folder in the root with some sbgn files which are not possible to open in SBGN-ED - to be removed after all dependent pages are checked. There is "images/examples" folder for the Examples page - to be removed after all dependent pages are checked. All the examples should be kept in "downloads/examples" and the links on the Examples page are to be updated. Each example should be available in .sbgn and other formats.

**Comment by fbergmann** [comment]
Hello Alexander, It'd be great if you could let me know which files don't open .. maybe other tools would load them fine. 

thanks
Frank

**Comment by amazein** [comment]
Hi Frank, 
I think all of the sbgnml files we have are in 0.3 format and those can be opened in Newt. Irina kindly agreed to provide some of them in 0.2 format. Right now only one example is available with different download options: https://sbgn.github.io/examples#repressilator-pd
What we could do is add 0.2 to the set (name files correspondingly), and then decide which one to offer for downloading.
Though, the issue created here is not about that. I simply wanted to keep track of the multiple "examples" folders that were created. After going through all the examples and providing files in different formats as with the repressilator, we can remove the two other folders and keep only "downloads/examples".

**Comment by amazein** [comment]
Available .sbgn files are here:
https://github.com/sbgn/sbgn.github.io/tree/master/examples

**Comment by vtoure** [comment]
Hi Alexander,
Some of these examples can be found in the libSBGN milestone 2 with the 0.2 version: https://github.com/sbgn/libsbgn/releases
