### ISSUE TITLE
Link for the only tool that converts SBML to SBGN is outdated on website

### ISSUE THREAD

**Issue by shoepfl** [sbgn/sbgn.github.io#8]
Dear SBGN team,

the link on the website to [CySBGN](http://www.ebi.ac.uk/saezrodriguez/cno/cysbgn/) does not work anymore and I was not able to find CySBGN elsewere in the internet. Could you please update the link or list a new converter for SBML->SBGN conversion. I think this is the most important conversion that has to be made?

Best,

Sebastian

**Comment by cannin** [comment]
@shoepfl Links fixed; best to have discussion on the libsbgn thread regarding the conversions
